In [1]:
import numpy as np

In [2]:
def fn(x):
    print(x/x.sum())

In [3]:
a = np.array([2.0,1.0,0.1])
fn(a)

[0.64516129 0.32258065 0.03225806]


In [4]:
def softmax(x):
    e = np.exp(x)
    print(e)
    print(e/np.sum(e))

In [5]:
a = np.arraya = np.array([2.0,1.0,0.1])
# fn(a)
softmax(a) # 확률높은곳에 가중치 
# e = 2.718 어쩌구 저쩌구
# 위에 값 e^2
# 아래값은 위 값에 a데이터 합을 나눈 것

[7.3890561  2.71828183 1.10517092]
[0.65900114 0.24243297 0.09856589]


weight값을 한번에 계산하게 만들어서 softmax로 확률값을 나오게 한다. 기억할 것.

미분분류 3가지면 3번수행. w가 3개가 나옴. (로지스틱에서)

한 방에 하기위해 매트릭스로 잡고 matmul함. 
softmax를 통과하면 확률이 나옴. 
확률이 큰쪽으로 다중분류 채택.