In [3]:
import numpy as np

In [6]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)

array5 = array3d.reshape(-1,1)
print(array5)
array6=array5.tolist()
print(array6)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]


In [11]:
array1d = np.arange(0,10)
array3 = array1d[array1d>5]

array3

In [16]:
name_array = np.array(['John','Mike','Sarah','Kate'])
score_array = np.array([78,11,21,11])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[1 3 2 0]
['Mike' 'Kate' 'Sarah' 'John']
