In [ ]:
numpy
파이썬에서 행렬 데이터를 관리하기 위해 제공되는 라이브러리
일반적인 프로그래밍에서 데이터를 다루는 방식이 아닌 수학의 행렬 데이터를 다루는 방식으로 데이터를 관리한다.


pandas
numpy는 수학에서 행렬을 다루기 위해 만든 라이브러리이다.
하지만 데이터를 다룰 때 좀 더 많은 기능이 필요하기 때문에 추가로 만든 라이브러리이다.
데이터 사이언스 분야에서 가장 핵심이 되는 라이브러리
데이터 분석, 시각화, 전처리, 가공, 변환 등등 많은 기능을 가지고 있다.


scikit-learn

언패킹


---

#추가
print(list1)
list1.append(70)
print(list1)
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 60, 70]

---

# 다수의 값을 동시에 추가하기
list1.extend([80,90,100])

---

# 삽입
# 삽입할 위치, 삽입할 값
list1.insert(4, 41)

---

#삭제. 인덱스를 통한 삭제
del list1[4]

---

# 삭제 값을 통한 삭제.
# 동일한 값이 있을 경우에는 제일 좌측의 값이 삭제된다.
list1.remove(70)

---

import numpy as np

list3 = list1 + list2
list4 = list1 * 3

---

array3 = array1 + array2
array4 = array1 * 3

---

print(list1) # ,로 비교
print(array1) # 띄어쓰기로 비교

---

#nd = n dimension

---

array1 = np.array([True, 100, 11.11, '문자열'])
# ndarray는 같은 타입의 값만 담을 수 있다.
# 다양한 타입의 값이 섞여져 있을 경우 더 많은 값의 종류를 표현할 수 있는 형태로 변환된다.
# 논리형 -> 정수 -> 실수 -> 문자열

---

#생성시 타입을 지정할 수 있다.
# 정수 : int, 실수: float, 논리: bool, 문자열: str
array2 = np.array([0, 1, 2, 3, 4], dtype = 'float')

---

#행렬의 타입확인
array4 = np.array([0,1,2,3,4])
print(array4.dtype)

---

# 행렬의 타입을 변경한다. 더 많은 값을 가질 수 있는 타입으로 변경 가능.
array5 = array4.astype('str')
print(array5.dtype)

---

# 0 행렬 : 0으로 구성된 행렬
array2 = np.zeros([3,4])
display(array2)

---

# 1로 채워진 행렬
array4 = np.ones([3,4])
display(array4)

---

# 7로 채워진 5개짜리 1차원 행렬
array5 = np.full(5,7)
display(array5)

#7이 채워진 3행 4열 2차원 행렬
array6 = np.full([3,4], 7)
display(array6)

---

# 특정 범위에 해당하는 값을 가지고 있는 1차원 행렬 생성
# range와 같음
# 0 ~ 6 -1 까지
array7 = np.arange(6)
display(array7)

# 3~ 13 -1 까지, 3씩 증가
array8 = np.arange(3,13, 3)
display(array8)

---

#행렬과 행렬의 연산
# 행렬의 각 원소를 1:1 매칭하여 연산하고 그 결과가 담겨 있는 행렬을 반환한다.
# 연산을 하는 두 행렬은 행과 열이 일치해야 한다.

# 행렬과 숫자간의 연산
# 행렬의 각 원소에 지정된 값을 연산한다.

---


색인과 슬라이싱
색인 : 원하는 값 하나를 가져오는 것.
슬라이싱 : 원하는 부분을 발췌하는 것.

---

# 2 ~ 6 -1 까지
display(list1[2:6])
display(array1[2:6])

---

list2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 2행 3열 데이터를 가져온다.
display(list2d[1][2])
display(array2d[1][2])
display(array2d[1, 2]) 
#[][]과  [,]에는 차이점이 있다.
6
6
6

# 슬라이싱
# 1 ~ 3 -1행, 1 ~ 3 -1열의 데이터를 가져온다.
print(list2d[1:3][1:3])
print(array2d[1:3][1:3]) # 프로그래밍언어에서의 접근
print(array2d[1:3, 1:3]) # 수학에서의 접근, 0행 0열 발췌 가능
#일관성 유지를 위해 
[[7, 8, 9]]
[[7 8 9]]
[[5 6]
 [8 9]]

---

# 테스트를 위한 새로운 행렬을 생성한다.
array1 = np.array([10, 20, 30, 40, 50])
array1
=
array([10, 20, 30, 40, 50])

# True나 False를 지정한다.
a1 = [True, False, True, False, True]
array2 = array1[a1]
array2
=
array([10, 30, 50])

# True나 False 구성된 요소를 넣어서 True자리에 해당하는 것만 가져오는 것을 이용해 검색 기능을 만들 수 있다.
array1 = np.arange(100)
display(array1)

array2 = array1 % 3 == 0
array2

array1[array2] #**어떤 조건에 만족하는 원소만 검색.**

array1[array1 % 3 == 0]

---

행렬의 차원을 변경

# 1차원 -> 2차원으로 변환
array2 = array1.reshape(3, 5)
array2 #행렬의 열의 개수 같아야 함.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 2차원 -> 1차원
# array3 = array2.reshape(10)
# display(array3)
# ValueError: cannot reshape array of size 15 into shape (10,)

---

# 2차원 -> 1차원
array3 = array2.reshape(15)
display(array3)

array4 = array2.reshape(-1) # 모든 원소의 개수를 가지고 1차원행렬을 만들어줌
display(array4)
=

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

---

통계함수

# 행렬이 제공하는 함수 사용하기
mean1 = array1.mean()
# numpy가 제공하는 함수 사용하기
mean2 = np.mean(array1)

print(mean1)
print(mean2)
=
7.0
7.0

---

로또 번호 추첨해보기...

# 1 ~ 45까지 가지고 있는 행렬을 생성한다.
array1 = np.arange(1, 46)
array1

for _ in range(10):
    array2 = np.random.permutation(array1)
    array3 = array2[:6]
    array3.sort()
    display(array3)

---

Series
값과 행렬로 구성된 1열 데이터
특성 하나의 데이터

Series 생성
series는 list, tuple, ndarray로 생성할 수 있다.
list, tuple인 경우에는 ndarray 로 생성한 다음 관리한다.
ndarray인 경우에는 해당 행렬 데이터를 관리한다.

---

Series가 관리하는 데이터에 접근하기
print(s1[0])
print(s1[1])
print(s1[2])
#  **[]는 인덱스 지칭하는 것.**

---

# 관리하는 값들은 모두 가져온다.
array1 = s1.values

---

# index를 추출한다.
array2 = s1.index
print(type(array2))
print(array2)
print(list(array2))

# 활용 ex)  나이 컬럼 >= 30, index 삭제.
# 조건식으로 추출

---

index 지정하기¶
Series 생성시 index를 지정하지 않으면 0부터 1씩 증가되는 값으로 지정된다.
index를 지정하고 싶다면 생성시 지정하거나 생성 후 필요할 때 지정할 수 있다.

---

#  생성한 Series에 인덱스를 변경한다.
# 새롭게 설정하는 인덱스의 갯수는 Series의 전체 행의 갯수와 일치해야 한다.
s1.index = ['값1','값2','값3']
s1

# 생성할 때 Index를 지정한다.
s2 = pd.Series([1000, 2000, 3000], index = ['값1','값2','값3'])
s2

---

값을 가져온다.
# index가 숫자로 되어 있을 경우 숫자를 지정하면 순서가 아닌 index 값을 통해 접근한다.
print(s1[0])
print(s1[1])
print(s1[2])

s2 = pd.Series([10, 20, 30, 40, 50], index=[3,0,4,1,2])
s2

# index를 지정하더라도 숫자로 구성되어 있으면 []의 숫자는 순서가 아닌 index 값을 의미한다.
print(s2[0])
print(s2[1])
print(s2[2])

# 인덱스가 문자열인 Series
a1 = ['값1', '값2', '값3', '값4', '값5']
s3 = pd.Series([10, 20, 30, 40, 50], index = a1)
s3
=
값1    10
값2    20
값3    30
값4    40
값5    50
dtype: int64

# index가 숫자가 아닌 Series에 숫자를 통해 접근을 하게 되면 순서에 해당한다.
# 0부터 1씩 증가
print(s3[0])
print(s3[1])
print(s3[2])
# index에 숫자를 넣을 경우와 문자를 넣을 경우 차이.

---

Series의 연산¶
Series는 내부적으로 1차원 ndarray를 관리하기 떄문에 연산 등의 작업은 ndarray와 동일하다.
#Series와 Series 연산
# 각 Series의 데이터를 1:1 매칭하여 연산을 한다.
# 개수가 다르면(성립이 안될 때) NaN를 결과값으로 설정한다.

# 개수가 다른 두 Series의 연산
# Pandas는 연산이 성립하지 않는 상황이라면 오류가 발생하는 것이 아니라 
# NaN이라는 값을 결과로 지정한다.
# NaN : Not a Number. 결측치를 의미하는 값이다.
# 결측치 : 측정이 되지 않는 값. 값이 비어있는 공간.

---

# Series와 특정 값의 계산
s20 = s1 + 10
s21 = s1 - 10
s22 = s1 * 10
s23 = s1 // 10

print(s20)
print(s21)
print(s22)
print(s23)
=
0    20
1    30
2    40
3    50
4    60
dtype: int64
0     0
1    10
2    20
3    30
4    40
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64

---

r1 = s1>30
r1
=
0    False
1    False
2    False
3     True
4     True
dtype: bool

---

슬라이싱
s1 = pd.Series([10, 20, 30, 40, 50], index=(['a1', 'a2', 'a3', 'a4', 'a5']))
s1
=
a1    10
a2    20
a3    30
a4    40
a5    50
dtype: int64

# a2 ~ a4까지
s2 = s1['a2' : 'a4']
s2

# a1, a3, a5만 가져온다.
# 원하는 것만 골라서 가져온다.
s4 = s1[['a1', 'a3', 'a5']]

# 순서 인덱스
# 0, 2, 4
s5 = s1[[0, 2, 4]]

---

# True나 False를 넣으면 True자리에 해당하는 것만 추출된다.
# 단 데이터의 개수와 일치해야 한다.
s6 = s1[[True, False, True, False, True]]

---

#조건에 따라 가져온다.
s7 = s1 > 40
s7
=
a1    False
a2    False
a3    False
a4    False
a5     True
dtype: bool

---

s8 = s1[s7]
s8

---

s9 = s1[s1 > 30]
#대괄호 안 연산에서 True/False -> list or ndarray 결과값을 다시 []안에 넣어서 True/False값 연산.

---

DataFrame
2차원 행렬 데이터를 행렬 형태가 아닌 테이블 형태로 관리할 수 있도록 제공되는 요소
DataFrame 컬럼 하나는 하나의 Series로 구성되어 있으며 다수의 Series들을 모아 하나의 DataFrame으로 관리한다.
DataFrame은 데이터의 특성 만큼의 Series로 구성된다.


데이터 프레임 생성
2차원 리스트
리스트를 가지고 있는 딕셔너리
딕셔너리를 가지고 있는 리스트
외부 파일(csv, 엑셀, spss 등)
웹문서의 table tag
데이터 베이스의 테이블
기타 등등

# 2차원 리스트를 통한 생성
# 내부의 각 리스트의 인덱스가 일치하는 것 끼리 모아 Series 만든다.
# 데이터 개수가 다르게 되어 있을 경우에는 비어있는 곳은 결측치로 채워진다.

---

# 컬럼 이름에 사용한 이름
column_list = ['번호', '성별', '국어', '영어', '수학', '과학']
# 인덱스에 사용할 이름
index_list = ['학생1','학생2','학생3','학생4','학생5','학생6']

# 생성되어 있는 데이터 프레임에 인덱스와 컬럼이름을 설정한다.
df1.columns = column_list # 이름 편할 걸로 고칠 것.
df1.index = index_list
df1

# 생성시 인덱스와 칼럼 이름을 지정한다.
df2 = pd.DataFrame(list1, columns = column_list, index = index_list)
df2

---

# 리스트를 가지고 있는 딕셔너리를 통한 생성
# 딕셔너리에 지정한 이름이 컬럼의 이름으로 결정된다.
# 데이터의 수가 다르게 되어있으면 오류가 발생하게 된다.
# 강사님이 자주 쓰는 방식임.

data1 = {
    '번호' : [1, 2, 3, 4],
    '성별' : ['남자','여자','남자','여자'],
    '국어' : [90, 91, 92, 93],
    '영어' : [80, 81, 82, 83],
    '수학' : [70, 71, 72, 73],
    #'과학' : [60, 61, 62, 63, 64]
    #'한국사' : [50, 51, 52]
}

df3 = pd.DataFrame(data1)
df3

---

# 딕셔너리를 가지고 있는 리스트
# 각 딕셔너리에 이름이 똑같은 것들끼리 모여 하나의 Series로 구성한다.
list3 = [
    {'번호' : 1, '이름' : '홍길동', '국어' : 100},
    {'번호' : 2, '이름' : '동길서', '국어' : 101},
    {'번호' : 3, '이름' : '백길남', '국어' : 102},
    {'번호' : 4, '이름' : '서길북', '국어' : 103},
    {'이름' : '황길동', '국어' : 199, '번호' : 5},
    {'번호' : 6, '이름' : '고길동', '귝어' : 105},
    {'번호' : 7, '이름' : '구길동', '국어' : 106, "영어" : 200}
]
df4 = pd.DataFrame(list3)
df4

---

# csv파일
# 데이터를 쉼표(,)로 구분한 데이터 양식

# 데이터 프레임 생성시 Encoding 오류가 발생하거나 생성된 데이터 프레임의 한글 데이터가 깨질 경우
# Pandas는 기본 인코딩이 UTF-8로 설정되어 있다. 허나 한국에서 엑셀을 통해 작업한  csv파일은 인코딩이
# euc-kr로 되어 있다.
# csv파일을 통해 생성시  encoding 오류가 나거나 한글이 깨져서 나오면 
# encoding을 euc-kr로 설정해서 시도해본다.

# 첫 번째 줄 데이터가 컬럼의 이름으로 결정된다.

df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

---

# **만약 첫번째 줄부터 데이터로 되어 있다면...**
# 원본 파일은 손대지 말자.
df2 = pd.read_csv('data/grade.csv', header=None, encoding='euc-kr')
df2.columns = ['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7']
df2

---

# 만약 3번째 줄의 데이터를 컬럼 이름으로 사용하겠다면...
# 단, 컬럼 이름으로 지정된 로우 위에 있는 데이터는 사라진다. 
df3 = pd.read_csv('data/grade.csv', encoding='euc-kr', header=2)
df3

---

# 엑셀 파일을 통한 데이터 프레임 생성
# sheet_name : 문자열을 넣을 경우 sheet의 이름이 되고 숫자를 넣을 경우
# sheet의 순서(0부터 시작)을  의미한다.
# 생략 시 첫번째 시트로 설정된다.

#df1 = pd.read_excel('data/grade.xlsx')
#df1 = pd.read_excel('data/grade.xlsx', sheet_name = 0)
df1 = pd.read_excel('data/grade.xlsx', sheet_name = 'grade')
df1

---


데이터 프레임의 정보를 확인한다.
데이터 프레임이 생성되었다면 데이터는 구조적인 문제는 없다.
데이터 프레임의 정보를 확인한다는 의미는 잘못된 데이터의 존재 여부를 확인함이 목적이다.

결측치 : 측정이 결여된 수치. 측정되지 않는 데이터. 파일에는 빈칸으로 되어 있고 데이터 프레임을 출력하면 Na나 NaN으로 표시된다.
이상치 : 정상값이 아닌 데이터.
몇몇 결함 데이터 보정 가능.(1-2 정확도 차이는 갠츈(중간값, 평균값)ㅋㅋ, 왜곡된 데이터를 집어넣는 것. 누구나 납득할 수 있는 객관적인 사유 필요.)
제거하게되면 정보량이 줄어드는 것.

---

# 행과 컬럼의 수를 파악한다.
size = df1.shape
print(size)
print(f'행 : {size[0]}')
print(f'열 : {size[1]}')

---

# 상위 5개를 추출한다.(한 번 찍어볼 때 or ()이 많은 순으로 뽑아올 때)
display(df1.head())
#하위 5개를 추출한다.
display(df1.tail())


# 상위 n개
display(df1.head(3))
# 하위 n개
display(df1.tail(3))

---

# 컬럼의 이름을 가져온다. # 반복문 이용 가능.
a1 = df1.columns
a1

---

#  인덱스의 이름을 가져온다.
a2 = df1.index
print(list(a2))

# 데이터 프레임의 요약 정보
# 891 entries : row가 891개 있다는 뜻이다.
# total 12 columns : 컬럼이 12개 있다는 뜻이다.
# Column : 데이터 프레임을 구성하는 컬럼의 이름.
# Non-Null Count : 결측치가 아닌 데이터의 수.
# **Dtype** : 컬럼에 저장되어 있는 값의 타입.
# int(정수), float(실수), **object(문자)**, datetime(시간)이 들어갈 수 있다.


df1.info()
=

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

---

# 각 컬럼의 결측치 개수를 파악
# isna : 각 컬럼의 데이터를 결측치는 True. 결측치가 아닌 것은 False로 된 새로운 데이터 프레임을 생성한다.
# sum : 각 컬럼별 총합을 구한다. 만약 True나 False로 구성되어 있다면 True를 1, False를 0으로 취급하여 합산한다.

df1.isna().sum() # 결측치가 몇 개인지 셀 수 있다. 

---

데이터의 종류
레이블형, 카테고리형 : 값의 종류가 정해져 있는 값(혈액형, 성별, 지하철 호선 등등) => 어떠한 종류의 값 저장되어 있는지 확인.
범위형 데이터 : 값의 범위(최소와 최대가 존재하는 값(나이, 키, 몸무게 등등)) => 최소와 최댓값을 확인. 이상치 찾는 것.
데이터의 종류에 따라 통계값을 해석해야 한다. 알아봐야하는 데이터가 종류에 따라 다르다!

# 요약 통계 정보
# 데이터 프레임 내의 숫자 타입 컬럼들만 모아 요약 통계 정보를 제공한다.
# 잘못된 데이터가 있는지 확인하기 위해 씀.
# Survived정보의 경우 의미가 있나? Category형 데이터.

df1.describe()

---

# 범위형 데이터에 대한 요약 통계 정보.
# 이상치 확인 가능
# count : 결측치를 제외한 데이터의 개수
# mean : 결측치를 제외한 평균
# std : 결측치를 제외한 표준편차
# **min** : 결측치를 제외한 최소값
# 25% : 최대, 최소 범위안에 25% 위치의 값(존재하지 않을 수 있다.)
# 50% : 최대, 최소 범위안에 50% 위치의 값(존재하지 않을 수 있다.)
# 75% : 최대, 최소 범위안에 75% 위치의 값(존재하지 않을 수 있다.)
# **max** : 결측치를 제외한 최대값

#min과 max를 통해 정상 범위에 벗어나는 데이터가 있는지 확인한다.(극단치 존재 여부도 **확인**해야 함.)

df1[['Age', 'Fare']].describe()

---

# 카테고리(레이블)형 데이터 (.describe함수도 좋지만..)
# count : 결측치를 제외한 데이터의 개수
# unique : 값의 종류
# top : 가장 많이 저장되어 있는 값
# freq : 가장 많이 저장되어 있는 값이 몇 개 저장되어 있는지.
# 요약 통계 정보는 숫자 컬럼인 경우에는 범위형 데이터로 취급해 보여주게 되고 문자열이라고 하더라도 어떠한 데이터가 저장되어 있는지
# 알 수 없기 때문에 이상치 존재 여부를 확인하기가 어렵다.

#df1['Pclass']
df1['Embarked'].describe() # 이걸로 예상치 찾는 것 어려울 수 있음. 등록자의 실수로. ex) count - 혈액형
=
count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

---

특정 위치의 값에 접근한다.

df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.index = ['학생1', '학생2', '학생3', '학생4', '학생5']
df1
# columns은 독립변수(순서가 있는 것이 아님). 직접적인 상관관계는 없다고 봐야 함(악영향 -> 노이즈). -> 있다면 종속변수.
#머신러닝에서 최대한 독립변수인 것을 유지하는게 중요.
# 행은 순서에 대한 개념 존재. 열은 없다.


# 특정 컬럼(Series)를 가져온다.
s1 = df1['국어']

# 특정 행을 추출한다(index)
r1 = df1.loc['학생3']

# 특정 행을 가져온다(순서. 0부터 시작)
r2 = df1.iloc[2]

# 원하는 위치의 값을 가져온다.
v1 = df1['국어']['학생3']
v1
#국어라는 열에 학생3이라는 행. 열 -> 행 순서.

v2 = df1['국어','학생3'] # ndarray에선 가능했음. 열 행이기 때문에 허용하지 않음.
v2
=
KeyError: ('국어', '학생3')

# 행, 열 접근
v3 = df1.loc['학생3']['국어']

v4 = df1.loc['학생3', '국어'] # 이거 왜 나오지?

# 순서( 3번째 행에 4번째 열)
v5 = df1.iloc[2][3]

v6 = df1.iloc[2, 3] # 행열로 접근 시 가능.

---

# 열 행 접근 방식으로 값을 설정한다.
df1['국어']['학생3'] = 1000
df1
# 새로 복제한 '국어'프레임을 복제해 값을 만듦.
# 원본 데이터에서 값을 추출해서 값이 바뀜.
-
# 행 열 접근 (index)
df1.loc['학생3']['영어'] = 2000
df1
# 값이 안바뀜.???? 접근하는 것.
-
# 이전에 본 표기 기법은 그것에 해당하는 것들을 추출하여 새로운 데이터 프레임을 생성해서 반환한다.(발췌)
# 아래의 표기 기법은 해당 데이터 프레임에 직접 접근을 한다.
# 강사님은 무조건 쉼표 찍는 걸로 씀.
# 데이터 집어넣는 건 다름. 행 열 구조로 접근할 때만.
df1.loc['학생3', '영어'] = 2000
df1
-
df1.iloc[2, 5] = 3000
df1
# 행 열 접근 시에는 이게 나을듯.

이름	학년	성별	국어	영어	수학	과학
학생1	철수	1	남자	98	NaN	88.0	64.0
학생2	영희	2	여자	88	90.0	62.0	72.0
학생3	민수	1	남자	1000	2000.0	3000.0	NaN
학생4	수현	3	여자	63	60.0	31.0	70.0
학생5	호영	4	남자	120	50.0	NaN	88.0