# 추가된 패키지
* from sklearn.preprocessing import StandardScaler, MinMaxScaler
* from sklearn.pipeline import make_pipeline

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.metrics import r2_score# 선형 모델(Linear Models)
from sklearn.datasets import load_boston, load_iris
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import make_pipeline
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

## 보스턴 데이터 가져오기

In [2]:
boston = load_boston()

## 보스턴 데이터 프레임으로 만들기

In [15]:
boston_df = pd.DataFrame(   boston['data'],columns=boston['feature_names'])
boston_df['MEDV'] =boston.target
boston_df.head(3)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7

## 특성데이터, 라벨 

In [4]:
x_data = boston_df.iloc[:,:-1]
y_data = boston_df.iloc[:,-1]

## train_set, test_set 나누기 train_test_split()

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, 
                                test_size=0.2,random_state=1)
# train, test set으로 분할(나눴음).

## 모델 파이프라인 만들기 make_pipeline()
## train_set 모델 핏 하기

In [6]:
# *steps : list of estimators.
model = make_pipeline(StandardScaler(), SGDRegressor())
model.fit(x_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdregressor', SGDRegressor())])

## train_set 결정계수 값 구하기

In [7]:
# 결정계수 값
model.score( x_train, y_train)

0.7277628569814881

## test_set 결정계수 값 구하기

In [8]:
model.score(x_test, y_test)

0.7621827741603763

## x_test.value 값

In [9]:
# 예측하기
x_test.values[0]

array([4.9320e-02, 3.3000e+01, 2.1800e+00, 0.0000e+00, 4.7200e-01,
       6.8490e+00, 7.0300e+01, 3.1827e+00, 7.0000e+00, 2.2200e+02,
       1.8400e+01, 3.9690e+02, 7.5300e+00])

## 예측하기

In [10]:
# 예측하기
model.predict([x_test.values[0]])

array([31.89506938])

## scaling위해 reshape하기

In [11]:
# 예측하기
model.predict(x_test.values[0].reshape(1,-1))

array([31.89506938])

In [12]:
# 딥러닝 tensorflow, pytorch배울텐데. 사이킷런처럼 파이프라인이 없음. 
# (사이킷런의 클래스처럼 만들어주는 케라스 제외하고)
#07.파일처럼 스케일링 수동으로 해줘야함.

In [13]:
x_data, y_data = iris_df.iloc[:,1:-1].values, iris_df.iloc[:,0].values
scaler_x = StandardScaler()
scaler_x.fit(x_data)
x_data_scale =  scaler_x.transform(x_data)

x_train, x_test, y_train, y_test = train_test_split(x_data_scale, y_data , test_size=0.2, random_state=1)

model_sgd = SGDRegressor()
model_sgd.fit(x_train, y_train)

print('train 점수:', model_sgd.score(x_train, y_train))
print('test 점수:', model_sgd.score(x_test, y_test))

pred = model_sgd.predict([[3.0, 1.4, 0.2]])
print('예측값:', pred)

NameError: name 'iris_df' is not defined

# 개인 과제
sl(target), feature(sw,pl,pw)
문제 : sw:3.0, pl:1.4, pw:0.2 인 경우 sl를 예측하시오
1. scale (standardscaring)
2. train, test
3. train, test score
4. 예측

강진영님

In [ ]:
# 로드하고
# 데이터프레임으로만들고, x는 columns는  
iris=load_iris()
iris_df=pd.DataFrame(iris['data'],columns=iris['feature_names'])
iris_df.head()

In [ ]:
# 컬럼값 지정하고,
# x데이터 지정
# y데이터 지정
iris_df.columns=['sl','sw','pl','pw']
x_data=iris_df[['sw','pl','pw']]
y_data=iris_df[['sl']]

In [ ]:
# 트레인, 테스트 나누고
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, 
                                test_size=0.2,random_state=1)

In [ ]:
# 파이프라인으로(스케일링, 경사하강법 때리고)
# x,y데이터 넣어주고
model=make_pipeline(StandardScaler(),SGDRegressor() )
model.fit(x_train, y_train)


In [ ]:
# 스코어 = 트레인 데이터를 새로 스케일링 작업
model.score(x_train, y_train)

In [ ]:
# 테스트도 스케일링 해야지
model.score(x_test, y_test)

In [ ]:
# p값에 넣어주는건? 
p=model.predict([[3.0,1.4,0.2]])

In [ ]:
p

# 교차검증(데이터가 작은 경우)
- 데이터를 두개로 분리하고 모델을 생성 및 검증하였지만, 데이터를 분리하였기 때문에 훈련에 사용할 수 있는 양도 작아지고, 분리가 잘 안된 경우에는 잘못된 검증이 될 수 있음
- 이럴 경우에는 테스트셋을 여러개로 구성하여 교차 검증을 진행
- cross_val_score() 함수는 교차 검증을 수행하여 모델을 검증


In [ ]:
# ![교차검증](img/교차검증.png)

In [ ]:
# cv값 디폴트 5개, 조절도 가능
# 각각 스코어(결정계수값)의 평균값을 최종 스코어로 나옴
# iris데이터임.

In [ ]:
r2scores = cross_val_score(model, x_data, y_data, cv=5, scoring='r2', verbose=1)
print(r2scores)
print(r2scores.mean())
# 교차검증값(score)이 나옴.
# 교차검증(score)평균값도 나옴.

#
1. 상관관계가 낮음 #점수가 안나옴.
2. 다중 공선성 
##### check
3. scale
4. 학습

# 다중 공선성
다중공선성 회귀 분석에서 사용된 모형의 일부 설명 변수가 다른 설명 변수와 상관 정도가 높아, 데이터 분석 시 부정적인 영향을 미치는 현상

X1은 일평균 음주량을 독립 변수 X2는 혈중 알코올 농도 둘의 상관관계가 높아 설명령이 약해진다 # 두가지를 특성데이터로 쓰기에는 상관관계가 높다?

회귀 모델에서 다중공선성을 파악할 수 있는 대표적인 방법은 VIF 임. 
VIF (Variance inflation Factors 분산팽창요인)
(사이킷런엔 없고 다른 패키지(from statsmodels.stats.outliers_influence import variance_inflation_factor
)에 있음)
- 안전 : VIF < 5
- 주의 : 5 < VIF < 10
- 위험 : 10 < VIF

개념을 잘 알고 있을 것

In [ ]:
boston_df.corr() # 상관관계 확인

In [ ]:
import seaborn as sb

In [ ]:
plt.figure(figsize=(10,8))
sb.heatmap(boston_df.corr(), annot=True, vmin = -1, vmax = 1, cmap='seismic') # -1<=상관계수값<=1
plt.show()

In [ ]:
boston_df.shape[1] # 14개 칼럼

In [ ]:
boston_df.values.shape # (ndarray) # 컬럼별 다중공선성을 ....

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif['VIF Factor']= [ variance_inflation_factor(boston_df.values, i )  for i in range( boston_df.shape[1] ) ]
vif['features'] = boston_df.columns
vif
# RM,PTRATIO을 제거해야함.
# 이후 score 확인.
# boston_df.values 전체 데이터를 확인하려고 한 것
# , 실제로는 특성데이터 x_data, y_data만 뽑아도됨.


 특성데이터가 많은경우: 다중공선성(컬럼제거), 타겟(라벨)에 상관관계가 낮은 컬럼

미쳤네 ㅋ.,ㅋ

In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
cal = fetch_california_housing()
cal

In [ ]:
cal['data'].shape

### 캘리포니아 주택 가격 데이터

| 속성 | 설명 |
|------|------|
| MedInc | 블록의 중간 소득 |
| HouseAge | 블록의 중간 주택 연도 |
| AveRooms | 자치시(town)별 비소매 상업지역 토지 비율 |
| AveBedrms | 찰스 강(Charles River)에 대한 변수 (강의 경계에 위치하면 1, 그렇지 않으면 0) |
| Population | 10,000,000당  일산화질소 농도 |
| AveOccup | 주택 1가구당 평균 방의 수 |
| Latitude | 1940년 이전에 건축된 소유주택 비율 |
| Longitude | 5개의 보스턴 고용 센터까지의 가중 거리 |


# 문제

### 캘리포니아 주택가격을 이용하여   crossvalidation 값을 구하시요.

### 다중공선성을 확인한후에 다중공선성이 높은 컬럼을 제외하고 학습하여 crossvalidation값을 확인하시요

### 문제가 좋지 못한 거긴 함. 학습이 제대로 안됨. 푸어데이터임.


성현님 답

In [ ]:
cal_df = pd.DataFrame(cal['data'], columns=cal['feature_names'])
cal_df['MEDV'] = cal['target']
cal_df.head()


성현님 답

In [ ]:


x_data = cal_df.iloc[:, :-1]
y_data = cal_df.iloc[:, -1]
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data.values, test_size = 0.2, random_state=1) # ndarray
model = make_pipeline(StandardScaler(),SGDRegressor(verbose=1))
model.fit(x_train, y_train)
r2scores = cross_val_score(model, x_data, y_data, cv=5, scoring='r2',verbose=1)
print(r2scores)
print(r2scores.mean())

cal_df.corr()

# 히트맵 그리기
plt.figure(figsize=(10,8))
sb.heatmap(cal_df.corr(), annot=True, vmin=-1, vmax=1, cmap='bwr')
plt.show()

# 다중공선성 확인
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif['VIF Factor']= [ variance_inflation_factor(cal_df.values, i )  for i in range( cal_df.shape[1] ) ]
vif['features'] = cal_df.columns
vif

# vif가 높은 Latitude, Longitude를 제외
cal_df = cal_df.drop(['Latitude', 'Longitude'], axis=1)
cal_df.head()

# 다시 교차검증
x_data = cal_df.iloc[:, :-1]
y_data = cal_df.iloc[:, -1]
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data.values, test_size = 0.2, random_state=1) # ndarray
model = make_pipeline(StandardScaler(),SGDRegressor(verbose=1))
model.fit(x_train, y_train)
r2scores = cross_val_score(model, x_data, y_data, cv=5, scoring='r2',verbose=1)
print(r2scores)
print(r2scores.mean())

# 다중공선성 재확인
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif['VIF Factor']= [ variance_inflation_factor(cal_df.values, i )  for i in range( cal_df.shape[1] ) ]
vif['features'] = cal_df.columns
vif