여러단계 weight, bias 구해서(거쳐서) 0을 구하는것 = 딥러닝

In [53]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier # 딥러닝 라이브러리
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
import sklearn.metrics as metrics
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



---
예시

In [3]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]])
y_data = np.array( [0,1,1,0])

In [10]:
model_logi = LogisticRegression(max_iter=1000,verbose=1)
model_logi.fit(x_data, y_data)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [11]:
model_logi.coef_

array([[0., 0.]])

In [12]:
model_logi.intercept_

array([0.])

In [13]:
model_logi.predict(x_data)

array([0, 0, 0, 0])

In [14]:
model_logi.score(x_data, y_data)
# 아무리 돌려도 예측을 하지 못한다.

0.5

In [ ]:
# 특성 데이터 2개.
# W: (2x1), b:1 개가 나옴
# 4x2(data) 2x10(b:10) 10x1(b:1) : 2x1
# 최종적으로 특성데이터는 2행 1열, bias는 한 개.
# **2x2 -> 2x1: 최종적으로 2x1 나와야함.**
# 처음에 특성데이터 갯수에 따라  맨 앞 숫자 2.
# 2x100 100x100
# 2x100 100x1f

---

## 딥러닝 라이브러리 MLPClassifier

In [19]:
# hidden_layer_sizes=(100,)  => : 2x1    : 2x100  100x1 (특성데이터 수 2개)
# hidden_layer_sizes=(2)  =>    : 2x2  2x1
# 4x2  2x2 ==> 4x2  2x1 ==> 4x1 (0,1,1,0)
# 4x2 2x100 ==> hidden_layer 4x100  100x1 ==> 4x1
model_mlp = MLPClassifier(max_iter=1000)

In [20]:
model_mlp.fit(x_data, y_data)

MLPClassifier(max_iter=1000)

In [21]:
model_mlp.predict(x_data)

array([0, 1, 1, 0])

---

In [23]:
model_mlp.coefs_ # weight값 리스트에 들어가 있음.

[array([[-3.04756154e-10, -9.26699417e-02, -1.06257282e-01,
         -6.55205020e-03,  5.02513644e-02, -3.32384007e-17,
         -5.63227627e-03, -5.40119393e-01,  5.35422365e-01,
          1.09886299e-01, -4.15613863e-01, -4.43351322e-01,
          6.33131446e-01,  1.39949011e-01,  1.51223138e-01,
          5.07026367e-01, -1.29289747e-01, -8.66053873e-02,
          4.59892335e-01,  4.78688213e-01, -2.72047546e-20,
          5.75837035e-01, -1.25984356e-05,  1.31819781e-01,
         -2.43389868e-07, -1.15435078e-07, -4.49132145e-01,
         -1.45006206e-07,  5.62984917e-01,  9.14032763e-02,
         -8.18143369e-01, -1.71030861e-01, -9.78580169e-11,
          1.73957469e-01, -4.96309652e-01,  4.40618925e-01,
         -4.60037574e-01,  2.77359491e-15,  1.90194934e-12,
          1.99852913e-01, -5.92540518e-14,  5.06852242e-02,
          2.22203038e-01, -1.21908564e-01, -4.00610714e-01,
          1.51327819e-07, -7.81526107e-14,  6.45752151e-22,
          4.92929927e-01,  6.35703957e-0

In [24]:
len(model_mlp.coefs_) # 리스트에 weight값 2개 들어가있음

2

In [31]:
model_mlp.coefs_[0].shape # weight : 2x100

(2, 100)

In [32]:
model_mlp.coefs_[1].shape # weight : 100x1

(100, 1)

In [38]:
len(model_mlp.intercepts_)

2

In [37]:
model_mlp.intercepts_[0].shape

(100,)

In [36]:
a= np.matmul(x_data, model_mlp.coefs_[0]) + model_mlp.intercepts_[0] # 4x2  2x100
# a -> relu(중간)///sigmoid(통과해야함)
b= np.matmul(a, model_mlp.coefs_[1]) + model_mlp.intercepts_[1] # 4x100  100x1
# b -> sigmoid(통과) 0.5보다 큰지 작은지 ... 0,1이 나옴.
b.shape # (0,1,1,0)
# 하나의 weight로 안되니까 여러 weight

(4, 1)

---

In [40]:
model_mlp1 = MLPClassifier(hidden_layer_sizes=(200,),max_iter=1000) # 2x200 200x1
model_mlp1.fit(x_data, y_data) # 2x200 200x1

MLPClassifier(hidden_layer_sizes=(200,), max_iter=1000)

In [41]:
model_mlp1.coefs_[0].shape

(2, 200)

In [42]:
model_mlp1.coefs_[1].shape

(200, 1)

In [43]:
model_mlp1.predict(x_data) # 4x2 2x200 ==> 4x200   200x1 ==> 4x1

array([0, 1, 1, 0])

In [ ]:
# 히든레이어수를 몇개를 잡아야하는가? 정해진 것 없다.
# 학습을 통해서 하이퍼파라미터임. 정해줘야함.


In [48]:
model_mlp2 = MLPClassifier(hidden_layer_sizes=(200,4),max_iter=1000)
model_mlp2.fit(x_data, y_data)

MLPClassifier(hidden_layer_sizes=(200, 4), max_iter=1000)

In [49]:
model_mlp2.coefs_[0].shape # 특성데이터 2개.

(2, 200)

In [50]:
model_mlp2.coefs_[1].shape

(200, 4)

In [51]:
model_mlp2.coefs_[2].shape

(4, 1)

In [ ]:
model_mpl2.predict(x_data) # 4x2 2x200 => 4x200 200x4 ==> 4x4 => 4x1 (3개의 히든레이어)

---
토론

In [ ]:
# 히든레이어를 몇개를 잡아줘야 학습이 잘될까? 얼마나 와이드? 정해진거 없다.
# 이미지 분류 쪽 하게되면 하이퍼파라미터 튜닝... 몇개 잡으니까 잘되더라
# 몰라요..몰라.. 튜닝해서 해보는 것임.
# 이렇게 했더니 잘되더라. 근데 모르겠따.
# 하이퍼파라미터 세세한 조정 쉬운것이 케라스, 파이토치, 텐서 등등 이 있음.
# 기본개념은 똑같다.
# 과적합도 확인해봐야한다. 후..
# 만들어진 배경, 히든레이어 얼마를 줘야하고 .. 이런건 튜닝 활동을 통해 해야됨. 
# 두가지는 잡고가자

---
예제

## 아이리스 데이터를 딥러닝으로 분류를 수행하시요
히든레이어는 총5개( 4x64, 64x32, 32x16, 16x1 )를 두고 

1000번 학습을 진행하시요.

4.9,3.0,1.4,0.2 에 대한 종분류 예측

In [66]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

x_data = iris['data']
y_data = iris['target']
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [67]:
# MLP모델 적용
model_mlp = MLPClassifier(hidden_layer_sizes=(64,32,16), max_iter=1000)
model_mlp.fit(x_data, y_data)

MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000)

In [76]:
# W1,W2,W3
print( len( model_mlp.coefs_) )
print( model_mlp.coefs_[0].shape ) # input layer
print( model_mlp.coefs_[1].shape ) # hidden
print( model_mlp.coefs_[2].shape ) # hidden
print( model_mlp.coefs_[3].shape ) # output layer
# 4x64, 64x32, 32x16, 16x3

4
(4, 64)
(64, 32)
(32, 16)
(16, 3)


In [77]:
model_mlp.predict(x_data)  

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
model_mlp.predict([[4.9,3.0,1.4,0.2]])

array([0])

In [80]:
model_mlp.predict_proba([[4.9,3.0,1.4,0.2]]).argmax(axis=1)
# 1x4  4x64 
# => 1x64 64x32
# => 1x32 32x16 
# => 1x16 16x3
# => 1x3(softmax)(0.8 0.2 0.1)

array([0], dtype=int64)

In [ ]:
# 라벨(y_data)를 내부적으로 onehot으로 바꿔줌.
# 16의 배수, 32의 배수로 감소되게끔 적다보니 잘되더라. 경험치에서 나온 것.

---