In [13]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier # 딥러닝 라이브러리
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import sklearn.metrics as metrics
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]])
y_data = np.array( [0,1,1,0])

In [7]:
model_logi = LogisticRegression(max_iter=1000, verbose=1)
model_logi.fit( x_data, y_data )

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [8]:
model_logi.coef_

array([[0., 0.]])

In [9]:
model_logi.intercept_

array([0.])

In [11]:
model_logi.predict(x_data)

array([0, 0, 0, 0])

In [12]:
model_logi.score(x_data, y_data)

0.5

## 딥러닝 라이브러리

In [ ]:
# 

In [16]:
model_mlp = MLPClassifier(max_iter=1000) #hidden_layer_sizes=(100,)  : 2x1   : 2x100   100x1
# 2x2 2x1  
# 4x2    2x2 ==> 4x2  2x1 ==> 4x1 (0,1,1,0)

In [17]:
model_mlp.fit( x_data,y_data)

MLPClassifier(max_iter=1000)

In [18]:
model_mlp.predict( x_data)

array([0, 1, 1, 0])

In [20]:
len( model_mlp.coefs_ )

2

In [22]:
model_mlp.coefs_[0].shape # w: 2x100

(2, 100)

In [23]:
model_mlp.coefs_[1].shape # w:100x1

(100, 1)

In [30]:
len( model_mlp.intercepts_ )

2

In [32]:
model_mlp.intercepts_[0].shape

(100,)

In [33]:
model_mlp.intercepts_[1].shape

(1,)

In [ ]:
4x2  2x100  ==> 4x100   100x1  == >4x1

In [34]:
a = np.matmul( x_data, model_mlp.coefs_[0]) + model_mlp.intercepts_[0]  # 4x2 2x100
# a --> relu 
b = np.matmul( a, model_mlp.coefs_[1] ) + model_mlp.intercepts_[1]  # 4x100 100x1
# b-->sigmoid
b.shape

(4, 1)

In [36]:
model_mlp1 = MLPClassifier(hidden_layer_sizes=(200,), max_iter=1000) #2x200 200x1
model_mlp1.fit( x_data,y_data)

MLPClassifier(hidden_layer_sizes=(200,), max_iter=1000)

In [37]:
model_mlp1.coefs_[0].shape

(2, 200)

In [38]:
model_mlp1.coefs_[1].shape

(200, 1)

In [39]:
model_mlp1.predict( x_data) # 4x2  2x200 ==> 4x200   200x1    ==>4x1  

array([0, 1, 1, 0])

In [40]:
model_mlp2 = MLPClassifier(hidden_layer_sizes=(200,4), max_iter=1000)
model_mlp2.fit( x_data,y_data)

MLPClassifier(hidden_layer_sizes=(200, 4), max_iter=1000)

In [41]:
model_mlp2.coefs_[0].shape

(2, 200)

In [42]:
model_mlp2.coefs_[1].shape

(200, 4)

In [43]:
model_mlp2.coefs_[2].shape

(4, 1)

In [44]:
model_mlp2.predict( x_data) # 4x2  2x200(sigmoid) => 4x200 200x4 (sigmoid)==> 4x4  4x1(sigmoid) => 4x1 

array([0, 1, 1, 0])

In [ ]:
아이리스 데이터를 딥러닝으로 분류를 수행하시요
히든레이어는 총5개( 4x64, 64x32, 32x16, 16x3 )를 두고 1000번 학습을 진행하시요.
4.9, 3.0, 1.4, 0.2 에 대한 종분류를 예측하시요 2조(50분 제출)

In [45]:
from sklearn.datasets import load_iris

# 데이터 불러오기
iris = load_iris()
iris.keys()

# x,y데이터 분류
x_data = iris['data']
y_data = iris['target']

In [48]:
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [46]:
# MLP모델 적용
model_mlp = MLPClassifier(hidden_layer_sizes=(64,32,16), max_iter=1000)
model_mlp.fit(x_data, y_data)

MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000)

In [53]:
# W1,W2,W3
print( len( model_mlp.coefs_) )
print( model_mlp.coefs_[0].shape ) # input layer
print( model_mlp.coefs_[1].shape ) # hidden
print( model_mlp.coefs_[2].shape ) # hidden
print( model_mlp.coefs_[3].shape ) # output layer
# 4x64, 64x32, 32x16, 16x3

4
(4, 64)
(64, 32)
(32, 16)
(16, 3)


In [49]:
model_mlp.predict(x_data)  

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [50]:
model_mlp.predict([[4.9,3.0,1.4,0.2]]) 1x4  4x64 =>1x64 64x32 1x32 32x16 => 1x16 16x3  1x3(softmax)(0.8 0.2 0.1)

array([0])

In [52]:
model_mlp.predict_proba([[4.9,3.0,1.4,0.2]]).argmax( axis=1)

array([0], dtype=int64)

In [ ]:


# 4.9, 3.0, 1.4, 0.2에 대한 예측

