In [1]:
import numpy as np

### 행렬의 차원을 변경

In [2]:
# 1차원 행렬을 생성한다.
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
# 1차원 -> 2차원으로 변환
array2 = array1.reshape(3, 5)
array2 #행렬의 열의 개수 같아야 함.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
# 2차원 -> 1차원
# array3 = array2.reshape(10)
# display(array3)
# ValueError: cannot reshape array of size 15 into shape (10,)

In [5]:
# 2차원 -> 1차원
array3 = array2.reshape(15)
display(array3)

array4 = array2.reshape(-1) 
# 모든 원소의 개수를 가지고 
##1차원행렬을 만들어줌
display(array4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 통계함수

In [6]:
array1 = np.arange(15).reshape(3, 5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
# 행렬이 제공하는 함수 사용하기
mean1 = array1.mean()
# numpy가 제공하는 함수 사용하기
mean2 = np.mean(array1)

print(mean1)
print(mean2)

7.0
7.0


### 로또 번호 추첨해보기...

In [8]:
# 1 ~ 45까지 가지고 있는 행렬을 생성한다.
array1 = np.arange(1, 46)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [64]:
for _ in range(10):
    array2 = np.random.permutation(array1)
    array3 = array2[:6]
    array3.sort()
    display(array3)

array([ 8, 15, 29, 30, 37, 40])

array([13, 14, 17, 22, 27, 32])

array([ 8, 29, 31, 40, 41, 43])

array([ 5,  6, 13, 36, 37, 41])

array([ 2,  4,  7, 11, 25, 30])

array([ 2,  6,  9, 15, 31, 45])

array([ 5,  6, 15, 27, 40, 44])

array([ 1, 12, 14, 32, 41, 45])

array([ 7, 10, 11, 24, 32, 43])

array([ 1,  3, 18, 26, 28, 36])