In [1]:
a1 = 100
a2 = 11.11
a3 = True
a4 = '문자열'
a5 = 10 + 3j 
a6 = 2_000_000_000 #정수

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

100
11.11
True
문자열
(10+3j)
2000000000


In [2]:
# 튜플생성
t1 = tuple()
t2 = ()
t3 = (1,2,3,4,5)
t4 = 1,2,3,4,5 #()없어도 가능

print(t1)
print(t2)
print(t3)
print(t4)

()
()
(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)


In [3]:
g1, g2, g3, g4, g5 = t4

In [4]:
print(g4)

4


In [8]:
import pandas as pd

d = {'col1': [1,2,3,4,5,6,7], 'col2': [11,12,13,14,15,16,17],\
    'col3' : [23,24,25,26,27,27,13]}
df = pd.DataFrame(data = d, index = [1,2,3,4,5,6,7])

print(df.columns[0:2])

Index(['col1', 'col2'], dtype='object')


In [9]:
 t1 = 10, 20, 30, 40, 50, 60, 70, 80, 90, 100


In [10]:
t1

(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)

In [11]:
t1[0]

10

In [12]:
t1[-1]

100

In [14]:
list1 = [10,20]

In [22]:
list1.append(60)
print(list1)

[10, 20, 60, 60, 60, 60, 60, 7, 0, 60, 60, 7, 0, 60]


In [23]:
list1.extend([60,7,0])
print(list1)

[10, 20, 60, 60, 60, 60, 60, 7, 0, 60, 60, 7, 0, 60, 60, 7, 0]


In [ ]:
list1.insert(4,41)

In [25]:
import numpy as np

In [26]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

array3 = array1 + array2
array4 = array1 * array2
array5 = array1 * 3
print(array3)
print(array4)
print(array5)

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 3  6  9 12 15]


In [30]:
array2 = np.array([0,1,2,3,4], dtype = 'float')
print(array2)

[0. 1. 2. 3. 4.]


In [31]:
array1 = np.zeros(5)
display(array1)

array([0., 0., 0., 0., 0.])

In [34]:
array5 = np.full([5,7],3)
display(array5)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [35]:
array7 = np.arange(6)
display(array7)

array([0, 1, 2, 3, 4, 5])

In [36]:
list2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [48]:
# 슬라이싱
# 1 ~ 3 -1행, 1 ~ 3 -1열의 데이터를 가져온다.
print(list2d[1:3][1:3])
print(array2d[1:2][1:2]) # 프로그래밍언어에서의 접근
print(array2d[1:3, 1:3]) # 수학에서의 접근, 0행 0열 발췌 가능
#일관성 유지를 위해 


[[7, 8, 9]]
[]
[[5 6]
 [8 9]]


In [49]:
array1 = np.arange(100)
display(array1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])